# description
name: "Grab Me"
description: "A contemporary, simple and convenient fast food based on Japanese authentic sushi"
keywords: "rolls, seafood"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://grabme.uk"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    - LICENSE
    - README.md
    - src
    - node_modules
